from __future__ import annotations

from django.core.management.base import BaseCommand, CommandError

from apps.graphrag.evaluation import (
    load_questions,
    seed_golden_cases_from_questions,
    write_golden_cases,
)


class Command(BaseCommand):
    help = "Generate reviewable GraphRAG golden cases from a list of questions."

    def add_arguments(self, parser):
        parser.add_argument(
            "--questions",
            required=True,
            help="Path to a .txt or .json file containing questions.",
        )
        parser.add_argument(
            "--out",
            required=True,
            help="Output path for generated golden cases JSON.",
        )
        parser.add_argument(
            "--limit",
            default="auto",
            help="Limit value passed to GraphRAG. Defaults to auto.",
        )
        parser.add_argument(
            "--enable",
            action="store_true",
            help="Write generated cases with enabled=true. Default is false for review safety.",
        )

    def handle(self, *args, **options):
        try:
            questions = load_questions(options["questions"])
        except Exception as exc:
            raise CommandError(f"Unable to load questions: {exc}") from exc

        if not questions:
            raise CommandError("No questions found.")

        try:
            cases = seed_golden_cases_from_questions(
                questions,
                enabled=bool(options["enable"]),
                limit=options["limit"],
            )
            write_golden_cases(
                cases,
                options["out"],
                description="Generated by seed_graphrag_cases. Review expected ids before enabling in CI.",
            )
        except Exception as exc:
            raise CommandError(f"Unable to seed GraphRAG golden cases: {exc}") from exc

        self.stdout.write(f"Generated {len(cases)} GraphRAG case(s): {options['out']}")
        self.stdout.write("Review expected ids and set enabled=true before using as a regression gate.")
